# Generated by Django 3.0.3 on 2020-02-26 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone_catalog',
            name='Address',
            field=models.CharField(max_length=110),
        ),
    ]
